### ISSUE TITLE
plugins: InventorySetups menu entry broken

### ISSUE THREAD

**Issue by Silverfeelin** [Owain94/OpenOSRS-RL-hub#42]
In version 0.0.7 of Inventory Setups you have replaced the `onMenuOptionClicked` binding, which removes the functionality added by the menu entry <kbd>Inv. Setup</kbd> in `onMenuEntryAdded`.

Could you re-introduce this feature?

Code link:
https://github.com/Owain94/OpenOSRS-RL-hub/commit/bc87a508f286e19c8cc521d5236bfcfe0046adfb#diff-ec78583b3a462903ccbf5eb7ef7f5d60L682-L686

Related PR: #16

**Comment by Owain94** [comment]
I borked the upstream merge indeed, sorry about that! I’ll add it back when I’m at my computer.

**Comment by Silverfeelin** [comment]
Thank you, and no problem at all.

**Comment by Silverfeelin** [comment]
@Owain94 Sorry to bother you again, but something still seems amiss with the new changes. When using the menu option, clicking on any item will put you back on the main tab.

Here's a short demonstration:
![](https://i.imgur.com/fDYeVH3.gif)

Probably some newly introduced state variable not being set from this action?
